# 2. NumPy 배열

* NumPy에는 ndarray라는 타입의 배열이 생성된다.
* ndarray는 같은 타입의 데이터만 저장할 수 있다.
* Python의 list보다 계산 속도가 빠르다.

In [1]:
# import하기
import numpy as np

## 2-1. np.array() 함수로 생성하기
### 1차원 배열 생성하기

In [2]:
# 1차원 배열
arr = np.array([1, 2, 3, 4]) #튜플도 가능하지만 리스트를 많이 사용
arr

array([1, 2, 3, 4])

In [3]:
# type 확인
type(arr)

numpy.ndarray

In [4]:
# array()에는 반드시 data가 1개 들어간다!
# np.array(1,2,3,4)#인자를 4개 준다.-> ERROR

In [5]:
# data type # 데이터 타입 확인
arr.dtype

dtype('int32')

In [6]:
# overflow 테스트
arr = np.array([2147483648, 2,3,4], dtype=np.int64)
arr

array([2147483648,          2,          3,          4], dtype=int64)

In [7]:
arr = np.array([1,2,3,4], dtype=float)
arr

array([1., 2., 3., 4.])

In [8]:
arr.dtype

dtype('float64')

In [9]:
# shape : 각 차원의 배열의 size(모양) 튜플로 출력(,)
arr.shape

(4,)

In [10]:
# size : 배열의 전체 element 수
arr.size

4

In [11]:
# ndim : 차원의 수
arr.ndim

1

In [12]:
arr = np.array([1, 2, 3,3.14])
arr

array([1.  , 2.  , 3.  , 3.14])

In [13]:
arr = np.array([1,2,3,3.14], dtype = int)
arr

array([1, 2, 3, 3])

In [14]:
# big-endian, little-endian
arr = np.array([1,3.14,'1234567890123456789012345678901234'])
arr # 모두 문자열로 출력

array(['1', '3.14', '1234567890123456789012345678901234'], dtype='<U34')

In [15]:
# 이미 있는 배열을 타입이 다른 다른 배열로 생성하기
new_arr = arr.astype(float)
new_arr

array([1.00000000e+00, 3.14000000e+00, 1.23456789e+33])

In [16]:
arr.dtype , new_arr.dtype

(dtype('<U34'), dtype('float64'))

In [17]:
arr = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
new_arr = np.array([arr,arr2])
new_arr

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

## 2차원 배열 생성하기

In [18]:
arr2 =np.array([[1,2,3,4],
                [5,6,7,8],
                [9,10,11,12]],dtype = float)
arr2

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [19]:
arr2.dtype, arr2.shape, arr2.size, arr2.ndim

(dtype('float64'), (3, 4), 12, 2)

In [20]:
new_arr = arr2.astype(int)
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## 2-2 np.arange() 함수로 생성하기

In [21]:
# 파이썬의 range
for i in range(10): # 0, 9
    print(i)

0
1
2
3
4
5
6
7
8
9


In [22]:
#np.array([1,2,3,4,5,6,7,8...100])
arr = np.arange(1,11,2)
arr
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None)

Return evenly spaced values within a given interval.

Values are generated within the half-open interval ``[start, stop)``
(in other words, the interval including `start` but excluding `stop`).
For integer arguments the function is equivalent to the Python built-in
`range` function, but returns an ndarray rather than a list.

When using a non-integer step, such as 0.1, the results will often not
be consistent.  It is better to use `numpy.linspace` for these cases.

Parameters
----------
start : number, optional
    Start of interval.  The interval includes this value.  The default
    start value is 0.
stop : number
    End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
step : number, optional
    Spacing between values.  For any output `out`, this is the distance
    between two adjacent values, ``out[i+1]

## 2차원 배열 생성하기

In [23]:
# 0-11
arr = np.arange(0,12)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr2 = arr.reshape((3,4)) # 배열의 사이즈와 맞지 않으면 ERROR
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
# 원본 배열의 shape을 변경하고자 할 경우
arr.shape = (3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

## 2-3. np.zeros() 함수

In [26]:
# 1차원 배열
arr =  np.zeros(4)
arr

array([0., 0., 0., 0.])

In [27]:
# 2차원 배열
arr2 = np.zeros((3,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## 2-4. np.ones()  함수 

In [28]:
# 1차원 배열
arr = np.ones(4)
arr

array([1., 1., 1., 1.])

In [29]:
# 2차원 배열
arr2 = np.ones((3,4))
arr2

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [47]:
arr = np.linspace(0,10,5)
arr

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
arr = np.linspace(0, 10) #기본 50개
arr

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [32]:
arr.shape

(50,)

In [33]:
arr2 = arr.reshape((10,5))
arr2

array([[ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653],
       [ 1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469],
       [ 2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286],
       [ 3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102],
       [ 4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918],
       [ 5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735],
       [ 6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551],
       [ 7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367],
       [ 8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184],
       [ 9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ]])

## 2-6 np.full() 함수

In [34]:
# 특정 값으로 배열을 생성할 경우
arr = np.full(4, 10)
arr

array([10, 10, 10, 10])

In [35]:
arr2 = np.full((3,4),10)
arr2

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [49]:
arr2 = np.full
arr2

<function numpy.full(shape, fill_value, dtype=None, order='C')>

## 2-7. np.eye() 함수

In [37]:
# 단위 행렬 (항등 행렬)
arr = np.eye(5)
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 2-8. np.random() 함수

In [38]:
import numpy as np

In [52]:
arr = np.random.rand(3)
arr

array([0.43857224, 0.0596779 , 0.39804426])

In [54]:
arr2 = np.random.rand(3,4)
arr2
np.random.rand?

Docstring:
rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random
Type:      builtin_function_or_method


In [72]:
arr = np.random.randint(low=10, high =20, size =10)
arr


array([12, 15, 12, 12, 19, 13, 12, 16, 17, 19])

In [42]:
arr2 = np.random.randint(1,5,size=(3,4))
arr2

array([[1, 1, 4, 3],
       [1, 4, 1, 1],
       [4, 1, 2, 1]])

In [43]:
# 일정한 랜덤값을 만드려면?
np.random.seed(123)
np.random.rand(3,4)

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477],
       [0.71946897, 0.42310646, 0.9807642 , 0.68482974],
       [0.4809319 , 0.39211752, 0.34317802, 0.72904971]])

## 2-9. Numpy 배열 Save & Load

In [44]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [45]:
np.save("my_arr",arr)

In [46]:
new_arr = np.load('my_arr.npy')
new_arr

array([0, 1, 2, 3, 4])